export const plans = [
  {
    id: "free",
    name: "Free",
    price: 0,
    duration_days: 0,
    max_uploads: 999999,
    storage_limit: 999999, // MB
    color: "#948979",
    perks: {
      "Đăng không giới hạn ảnh/video": true,
      "Tuỳ chỉnh nền và trang trí đầy đủ": true,
      "Hỗ trợ tuỳ chỉnh nâng cao": true,
      "Toàn quyền tuỳ chỉnh mọi tính năng": true,
      "Giới hạn upload ảnh 3MB": true,
      "Giới hạn upload video 7MB": true,
    },
    features: {
      custom_theme: true,
      select_friends: true,
      create_post: true,
      decorative: true,
      background: true,
      image_icon: true,
      music_icon: true,
      dev_tools: true,
      no_ads: false,
    },
    has_trial_offer: false,
    max_image_size: 3,
    max_video_size: 7
  },
  {
    id: "premium_lite",
    name: "Premium Lite",
    price: 10000,
    duration_days: 30,
    max_uploads: 999999,
    storage_limit: 999999,
    color: "#4DA8DA",
    perks: {
      "Mọi tính năng của gói Free": true,
      "Không có quảng cáo": true,
      "Giới hạn upload ảnh 5MB": true,
      "Giới hạn upload video 10MB": true,
    },
    features: {
      custom_theme: true,
      select_friends: true,
      create_post: true,
      decorative: true,
      background: true,
      image_icon: true,
      music_icon: true,
      dev_tools: true,
      no_ads: true,
    },
    has_trial_offer: false,
    max_image_size: 5,
    max_video_size: 10
  },
  {
    id: "premium",
    name: "Premium",
    price: 17000,
    duration_days: 30,
    max_uploads: 999999,
    storage_limit: 999999,
    color: "#52357B",
    perks: {
      "Mọi tính năng của gói Premium Lite": true,
      "Không có quảng cáo": true,
      "Hỗ trợ ưu tiên": true,
      "Giới hạn upload ảnh 7MB": true,
      "Giới hạn upload video 20MB": true,
    },
    features: {
      custom_theme: true,
      select_friends: true,
      create_post: true,
      decorative: true,
      background: true,
      image_icon: true,
      music_icon: true,
      dev_tools: true,
      no_ads: true,
    },
    has_trial_offer: false,
    max_image_size: 7,
    max_video_size: 20
  },
  {
    id: "pro_plus",
    name: "Pro Plus",
    price: 30000,
    duration_days: 90,
    max_uploads: 999999,
    storage_limit: 999999,
    color: "#626F47",
    perks: {
      "Mọi tính năng của gói Premium": true,
      "Không có quảng cáo": true,
      "Hỗ trợ ưu tiên 24/7": true,
      "Tối đa giới hạn upload ảnh và video (10MB / 25MB)": true,
    },
    features: {
      custom_theme: true,
      select_friends: true,
      create_post: true,
      decorative: true,
      background: true,
      image_icon: true,
      music_icon: true,
      dev_tools: true,
      no_ads: true,
    },
    has_trial_offer: true,
    max_image_size: 10,
    max_video_size: 25
  },
]; 